export interface SolicitacaoHoraExtraPorAprovador {

  id?: string,
  gef?:string,
  version?: number,
  funcionarioCodigo?: number,
  funcionarioNome?: string,
  dia?: Date,
  minutos?: number,
  solicitadoPor?: string,
  solicitadoEm?: string,
  observacao?: string,
  departamentoCodigo?: number,
  departamentoDescricao?: string,
  motivoCodigo?: number,
  motivoDescricao?: string,
  codigoGrupoEmpresa?: number,
  codigoEmpresa?: number,
  codigoFilial?: number,
  aguardandoAprovacao?: string,
  aprovadorCodigo?: number,
  aprovadorNome?: string,
  nivelMax?: number,
  nivelAprovar?: number,
  status?: string,
}
